apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myportal
  template:
    metadata:
      labels:
        app: myportal
    spec:
      containers:
      - name: myportal-container
        # Docker Hub의 퍼블릭 이미지 경로 지정
        image: stumna/myportal:latest 
        ports:
        - containerPort: 80 # myportal이 사용하는 포트 확인 필요
