apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myportal
  template:
    metadata:
      labels:
        app: myportal
    spec:
      containers:
        - name: myportal
          image: stumna/myportal:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  # 가장 간단하게 외부로 노출하는 타입
  type: LoadBalancer
  selector:
    app: myportal
  ports:
    - protocol: TCP
      port: 80        # 브라우저로 접속할 포트 (http://...)
      targetPort: 8000  # 컨테이너 포트
