apiVersion: v1
kind: Service
metadata:
  name: myportal-service
spec:
  selector:
    app: myportal
  ports:
  - protocol: TCP
    port: 8080 # Service 포트
    targetPort: 80 # 컨테이너 포트 (Deployment에서 지정한 포트와 일치)
  type: NodePort # 또는 LoadBalancer (추가 설정 필요)
